/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Representation challenge. The challenge recipient is expected to solve challenge by signing it by pairwise
 * private key of given connection.
 */
export interface Challenge {
  /**
   * Id of challenge
   */
  challengeId?: string;
  /**
   * Challenge data. Recipient should decode the base64, sign its data and submit result as Solution.
   */
  challengeBase64?: string;
}
