/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object specifying how schema resource and whether the schema is already on the ledger, or whether new
 * schema should be written on the ledger.
 */
export interface CreateSchema {
  /**
   * Attributes contained in the schema. Must be specified foor both \"load\" and \"create\" method.
   */
  attributes?: Array<string>;
  /**
   * Valid values are \"load\" and \"create\". If you use \"load\", schema matching rest of request parameters
   * must already exist on the ledger. It must specify \"schemaLedgerId\" matching schema id on the ledger.
   * If you use \"create\", new schema will be written on the ledger.
   * Hence in this case you dont have too specify value of \"schemaLedgerId\".
   */
  method?: string;
  /**
   * Only when using \"load\" method. This must exactly match id of existing schema already present on the ledger.
   */
  schemaLedgerId?: string;
  /**
   * Only when using \"create\" method. Human readable name of the schema.
   */
  schemaName?: string;
  /**
   * Only when using \"create\" method. Must be in format <uint>.<uint>.<uint>
   */
  schemaVersion?: string;
}
