/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object specifying what data proof should requested from whom.
 */
export interface CreateProof {
  /**
   * List of attributes verifier is requesting from prover to prove.
   */
  attributes?: Array<string>;
  /**
   * Name given to created proof instance.
   */
  name?: string;
}
