/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object specifying for whom to issue what credential, with what values.
 */
export interface CreateCredential {
  /**
   * Ledger Id of credential definition the credential should be built on top of.
   */
  credDefId?: string;
  /**
   * The name we are assigning to instance of issued credential.
   */
  credentialName?: string;
  /**
   * key:value object where key is name of credential field, value is the assigned value in issued credential.
   * This object must contain same key as are attributes of schema of credential definition you are isssuing the credential on top of.
   */
  values?: any;
}
