/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateCredentialDef {
  /**
   * VCXS (REST) ID of Schema to build Credential Definition on top of.
   */
  schemaId?: string;
  /**
   * Name given to credential definitioon.
   */
  credDefName?: string;
}
