/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Credential {
  /**
   * Id of Credential as VCXR REST Resource.
   */
  id?: string;
  /**
   * VCXS (REST) ID of Connection where the Credential was sent to.
   */
  connectionId?: string;
  /**
   * Name given to the particular instance of issued credential.
   */
  credentialName?: string;
  /**
   * Ledger ID of Credential Definition on top of which the Credential was built.
   */
  credDefLedgerId?: string;
  /**
   * DID if credential isssuer
   */
  issuedDid?: string;
  /**
   * State of credential. 1=Initialized, 2=CredentialOfferSent, 3=CredentialRequestReceived, 4=Accepted
   */
  state?: number;
}
