/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Invitation {
  /**
   * Invitation string which can be processes by LibVCX method Connection.createWithInvite(...)
   */
  invitationString?: string;
}

export interface InvitationString {
  id: string;
  s: {
    d: string,
    dp: {
      d: string,
      k: string,
      s: string
    },
    l: string, // logo image
    n: string,
    publicDID: string,
    v: string
  };
  sa: object;
  sc: string;
  sm: string;
  t: string;
  threadId: null;
}
