/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Representation of VCXS proof resource.
 */
export interface Proof {
  /**
   * Id of Proof as VCXR REST Resource.
   */
  id?: string;

  /**
   * Connection id.
   */
  connectionId?: string;
  /**
   * Name given to proof instance.
   */
  proofName?: string;
  /**
   * List of attributes verifier is requesting from prover to prove.
   */
  requestedAttrs?: Array<ProofReqAttributes>;
  /**
   * Prediccates placing restrictions on how the proof can be constructed by prover.
   */
  requestedPredicates?: string;
  /**
   * DID of prover.
   */
  proverDid?: string;
  /**
   * State of proof:
   * 1=initialized,
   * 2=sent,
   * 3=received,
   * 4=accepted
   */
  state?: string;

  // tslint:disable-next-line: ban-types
  proofData?: Array<Object>;
}

export interface ProofReqAttributes {
  name: string;
}
