/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Representation of VCXS schema resource.
 */
export interface Schema {
  /**
   * Id of Schema as VCXR REST Resource.
   */
  id?: string;
  /**
   * Id of Schema on the ledger (the value of txnMetadata.txnId on ledger).
   */
  schemaLedgerId?: string;
  /**
   * Schema name on the ledger (is part of txnMetadata.txnId).
   */
  schemaName?: string;
  /**
   * List of schema attributes.
   */
  attributes?: Array<string>;
}
