/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object specifying whom too send what message.
 */
export interface SendMessage {
  /**
   * Content of message
   */
  msg?: string;
  /**
   * Type of message (use this to identify different kind of messages you might create in your domain)
   */
  type?: string;
  title?: string;
}
