/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Representation of data provided as solution to a challenge.
 */
export interface Solution {
  /**
   * Indicates whether the solution was correct.
   */
  success?: boolean;
  /**
   * Id of challenge
   */
  challengeId?: string;
  /**
   * Id of solution
   */
  solutionId?: string;
}
