/**
 * VCXS Swagger
 * VCXS - Verifiable Credential Exchange Service
 *
 * OpenAPI spec version: 1.1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';
import { Solution, Challenge } from 'src/app/models/models';
import { Configuration } from '../configuration';
import { BASE_PATH } from '../variables';

@Injectable({
  providedIn: 'root'
})
export class ProofsService {

  // protected basePath = 'https://api.oldmutual.myid.africa/api';
  basePath: string;
  public defaultHeaders = new HttpHeaders();
  public configuration: Configuration;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    // @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (!this.configuration) {
      this.configuration = new Configuration();
      this.basePath = basePath || this.configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }


  /**
   *
   * Create challenge for Connection specified by id
   * @param connectionId Identifier of connection
   * @param challengeId Identifier of challenge
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public challengeCreate(connectionId: string, challengeId: string, observe?: 'body', reportProgress?: boolean): Observable<Challenge>;
  public challengeCreate(
    connectionId: string, challengeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Challenge>>;
  public challengeCreate(
    connectionId: string, challengeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Challenge>>;
  public challengeCreate(
    connectionId: string, challengeId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (connectionId === null || connectionId === undefined) {
      throw new Error('Required parameter connectionId was null or undefined when calling challengeCreate.');
    }

    if (challengeId === null || challengeId === undefined) {
      throw new Error('Required parameter challengeId was null or undefined when calling challengeCreate.');
    }

    let headers = this.defaultHeaders;

    // authentication (BasicAuth) required
    if (this.configuration.username || this.configuration.password) {
      headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.post<Challenge>(
      `${this.basePath}/connections/${encodeURIComponent(String(connectionId))}/challenges/${encodeURIComponent(String(challengeId))}`,
      null,
      {
        withCredentials: this.configuration.withCredentials,
        headers,
        observe,
        reportProgress
      }
    );
  }

  /**
   *
   * Submits solution of Challenge specified by connectionId and challengeId.
   * @param connectionId Identifier of connection
   * @param challengeId Identifier of challenge
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public challengeSolutionCreate(
    connectionId: string, challengeId: string, observe?: 'body', reportProgress?: boolean): Observable<Solution>;
  public challengeSolutionCreate(
    connectionId: string, challengeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Solution>>;
  public challengeSolutionCreate(
    connectionId: string, challengeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Solution>>;
  public challengeSolutionCreate(
    connectionId: string, challengeId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (connectionId === null || connectionId === undefined) {
      throw new Error('Required parameter connectionId was null or undefined when calling challengeSolutionCreate.');
    }

    if (challengeId === null || challengeId === undefined) {
      throw new Error('Required parameter challengeId was null or undefined when calling challengeSolutionCreate.');
    }

    let headers = this.defaultHeaders;

    // authentication (BasicAuth) required
    if (this.configuration.username || this.configuration.password) {
      headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
    }

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    // tslint:disable-next-line: max-line-length
    return this.httpClient.post<Solution>(`${this.basePath}/connections/${encodeURIComponent(String(connectionId))}/challenges/${encodeURIComponent(String(challengeId))}/solutions`,
      null,
      {
        withCredentials: this.configuration.withCredentials,
        headers,
        observe,
        reportProgress
      }
    );
  }

}
